const PRODUCTS = [
  // ===== MERCEDES ACTROS MP4 =====
  { id: "MT-M001", brand: "Mercedes", price: 119, image: "images/m001.jpg",
    name: { en: "Long Step - Left (Actros MP4)", sq: "Shkallë Hyrëse e Gjatë - Majtas (Actros MP4)", mk: "Долга Влезна Скала - Лево (Actros MP4)" } },
  { id: "MT-M002", brand: "Mercedes", price: 27, image: "images/m002.jpg",
    name: { en: "Front Wheel Rear Mudguard - Outer Cheek Right", sq: "Mbrojtëse e Pasme e Rrotës së Përparme - Faqe e Jashtme Djathtas", mk: "Заден Калобран на Преден Тркал - Надворешна Страна Десно" } },
  { id: "MT-M003", brand: "Mercedes", price: 27, image: "images/m003.jpg",
    name: { en: "Front Wheel Rear Mudguard - Outer Cheek Left", sq: "Mbrojtëse e Pasme e Rrotës së Përparme - Faqe e Jashtme Majtas", mk: "Заден Калобран на Преден Тркал - Надворешна Страна Лево" } },
  { id: "MT-M004", brand: "Mercedes", price: 18.5, image: "images/m004.jpg",
    name: { en: "Curved Bumper - Right (1848/1851)", sq: "Bamper i Kthyer - Djathtas (1848/1851)", mk: "Свиткан Браник - Десно (1848/1851)" } },
  { id: "MT-M005", brand: "Mercedes", price: 18.5, image: "images/m005.jpg",
    name: { en: "Curved Bumper - Left (1848/1851)", sq: "Bamper i Kthyer - Majtas (1848/1851)", mk: "Свиткан Браник - Лево (1848/1851)" } },
  { id: "MT-M006", brand: "Mercedes", price: 159, image: "images/m006.jpg",
    name: { en: "Center Bumper (Actros MP4)", sq: "Bamper Qendror (Actros MP4)", mk: "Централен Браник (Actros MP4)" } },
  { id: "MT-M007", brand: "Mercedes", price: 14, image: "images/m007.jpg",
    name: { en: "Small Chrome Mirror Cover - Right", sq: "Kapak i Vogël i Pasqyrës (Nikel) - Djathtas", mk: "Мал Хромиран Капак за Огледало - Десно" } },
  { id: "MT-M008", brand: "Mercedes", price: 14, image: "images/m008.jpg",
    name: { en: "Small Chrome Mirror Cover - Left", sq: "Kapak i Vogël i Pasqyrës (Nikel) - Majtas", mk: "Мал Хромиран Капак за Огледало - Лево" } },
  { id: "MT-M009", brand: "Mercedes", price: 21, image: "images/m009.jpg",
    name: { en: "Large Mirror Cover - Right (Actros MP4)", sq: "Kapak i Madh i Pasqyrës - Djathtas", mk: "Голем Капак за Огледало - Десно" } },
  { id: "MT-M010", brand: "Mercedes", price: 50, image: "images/m010.jpg",
    name: { en: "Mega Headlight Lower Brow - Right", sq: "Vetull e Poshtme e Fenerit Mega - Djathtas", mk: "Долна Веѓа на Мега Фар - Десно" } },
  { id: "MT-M011", brand: "Mercedes", price: 50, image: "images/m011.jpg",
    name: { en: "Mega Headlight Lower Brow - Left", sq: "Vetull e Poshtme e Fenerit Mega - Majtas", mk: "Долна Веѓа на Мега Фар - Лево" } },
  { id: "MT-M012", brand: "Mercedes", price: 2, image: "images/m012.jpg",
    name: { en: "Headlight Brow Clip Pin", sq: "Pin Mbërthyese për Vetullën e Fenerit", mk: "Иглица за Веѓа на Фар" } },
  { id: "MT-M013", brand: "Mercedes", price: 177, image: "images/m013.jpg",
    name: { en: "Short Arm Mirror - Right (Actros MP4)", sq: "Pasqyrë me Krah të Shkurtër - Djathtas", mk: "Огледало со Краток Крак - Десно" } },
  { id: "MT-M014", brand: "Mercedes", price: 177, image: "images/m014.jpg",
    name: { en: "Short Arm Mirror - Left (Actros MP4)", sq: "Pasqyrë me Krah të Shkurtër - Majtas", mk: "Огледало со Краток Крак - Лево" } },
  { id: "MT-M015", brand: "Mercedes", price: 83, image: "images/m015.jpg",
    name: { en: "Headlight Housing - Right (Mega)", sq: "Foleja e Fenerit - Djathtas (Mega)", mk: "Куќиште на Фар - Десно (Мега)" } },
  { id: "MT-M016", brand: "Mercedes", price: 83, image: "images/m016.jpg",
    name: { en: "Headlight Housing - Left (Mega)", sq: "Foleja e Fenerit - Majtas (Mega)", mk: "Куќиште на Фар - Лево (Мега)" } },
  { id: "MT-M017", brand: "Mercedes", price: 75, image: "images/m017.jpg",
    name: { en: "Exterior Door Handle with Key - Right", sq: "Dorezë e Jashtme e Derës me Çelës - Djathtas", mk: "Надворешна Рачка на Врата со Клуч - Десно" } },
  { id: "MT-M018", brand: "Mercedes", price: 75, image: "images/m018.jpg",
    name: { en: "Exterior Door Handle with Key - Left", sq: "Dorezë e Jashtme e Derës me Çelës - Majtas", mk: "Надворешна Рачка на Врата со Клуч - Лево" } },
  { id: "MT-M019", brand: "Mercedes", price: 65, image: "images/m019.jpg",
    name: { en: "Fog Lamp - Right (Actros MP4)", sq: "Llambë Mjegullimbledhëse - Djathtas", mk: "Светилка за Магла - Десно" } },
  { id: "MT-M020", brand: "Mercedes", price: 65, image: "images/m020.jpg",
    name: { en: "Fog Lamp - Left (Actros MP4)", sq: "Llambë Mjegullimbledhëse - Majtas", mk: "Светилка за Магла - Лево" } },
  { id: "MT-M021", brand: "Mercedes", price: 31, image: "images/m021.jpg",
    name: { en: "Large Mirror Glass - Right (Actros/Arocs)", sq: "Xham i Madh i Pasqyrës - Djathtas", mk: "Големо Стакло за Огледало - Десно" } },
  { id: "MT-M022", brand: "Mercedes", price: 31, image: "images/m022.jpg",
    name: { en: "Large Mirror Glass - Left (Actros/Arocs)", sq: "Xham i Madh i Pasqyrës - Majtas", mk: "Големо Стакло за Огледало - Лево" } },
  { id: "MT-M023", brand: "Mercedes", price: 30, image: "images/m023.jpg",
    name: { en: "Small Mirror Glass - Right (Actros/Arocs)", sq: "Xham i Vogël i Pasqyrës - Djathtas", mk: "Мало Стакло за Огледало - Десно" } },
  { id: "MT-M024", brand: "Mercedes", price: 30, image: "images/m024.jpg",
    name: { en: "Small Mirror Glass - Left (Actros/Arocs)", sq: "Xham i Vogël i Pasqyrës - Majtas", mk: "Мало Стакло за Огледало - Лево" } },
  { id: "MT-M025", brand: "Mercedes", price: 3, image: "images/m025.jpg",
    name: { en: "Step Plastic Clip (Upper/Lower, R/L)", sq: "Mbërthyese Plastike e Shkallës (Lart/Poshtë)", mk: "Пластична Иглица за Скала" } },
  { id: "MT-M026", brand: "Mercedes", price: 9.5, image: "images/m026.jpg",
    name: { en: "Lower Step Plastic - Right", sq: "Plastikë e Poshtme e Shkallës - Djathtas", mk: "Долна Пластика на Скала - Десно" } },
  { id: "MT-M027", brand: "Mercedes", price: 9.5, image: "images/m027.jpg",
    name: { en: "Lower Step Plastic - Left", sq: "Plastikë e Poshtme e Shkallës - Majtas", mk: "Долна Пластика на Скала - Лево" } },
  { id: "MT-M028", brand: "Mercedes", price: 6.5, image: "images/m028.jpg",
    name: { en: "Tail Light Side Cover (Actros MP4)", sq: "Kapak Anësor i Llambës së Pasme", mk: "Страничен Капак на Задна Светилка" } },
  { id: "MT-M029", brand: "Mercedes", price: 119, image: "images/m029.jpg",
    name: { en: "Long Step (Actros MP4)", sq: "Shkallë Hyrëse e Gjatë (Actros MP4)", mk: "Долга Влезна Скала (Actros MP4)" } },
  { id: "MT-M030", brand: "Mercedes", price: 21, image: "images/m030.jpg",
    name: { en: "Long Bumper 1845 - Right (Gray)", sq: "Bamper i Gjatë 1845 - Djathtas (Gri)", mk: "Долг Браник 1845 - Десно (Сив)" } },

  // ===== MAN TGA / TGS / TGX / TGL =====
  { id: "MT-N001", brand: "MAN", price: 16, image: "images/n001.jpg",
    name: { en: "Upper Mudguard (TGA/TGS/TGX)", sq: "Mbrojtës i Sipërm i Blatit (TGA/TGS/TGX)", mk: "Горен Калобран (TGA/TGS/TGX)" } },
  { id: "MT-N002", brand: "MAN", price: 39, image: "images/n002.jpg",
    name: { en: "Rear Mudguard - Right/Left (TGA/TGS/TGX)", sq: "Mbrojtës i Pasmë i Blatit (TGA/TGS/TGX)", mk: "Заден Калобран (TGA/TGS/TGX)" } },
  { id: "MT-N003", brand: "MAN", price: 39, image: "images/n003.jpg",
    name: { en: "Front Mudguard - Right/Left (TGA/TGS/TGX)", sq: "Mbrojtës i Përparmë i Blatit (TGA/TGS/TGX)", mk: "Преден Калобран (TGA/TGS/TGX)" } },
  { id: "MT-N004", brand: "MAN", price: 16, image: "images/n004.jpg",
    name: { en: "Door Pull Handle - Right (TGS/TGX, with kit)", sq: "Dorezë Tërheqëse e Derës - Djathtas (me Kit Riparimi)", mk: "Внатрешна Рачка за Врата - Десно (со Поправка)" } },
  { id: "MT-N005", brand: "MAN", price: 16, image: "images/n005.jpg",
    name: { en: "Door Pull Handle - Left (TGS/TGX, with kit)", sq: "Dorezë Tërheqëse e Derës - Majtas (me Kit Riparimi)", mk: "Внатрешна Рачка за Врата - Лево (со Поправка)" } },
  { id: "MT-N006", brand: "MAN", price: 41, image: "images/n006.jpg",
    name: { en: "Exterior Door Handle with Key - Right (TGA/TGS/TGX/TGL)", sq: "Dorezë e Jashtme e Derës me Çelës - Djathtas", mk: "Надворешна Рачка на Врата со Клуч - Десно" } },
  { id: "MT-N007", brand: "MAN", price: 41, image: "images/n007.jpg",
    name: { en: "Exterior Door Handle with Key - Left (TGA/TGS/TGX/TGL)", sq: "Dorezë e Jashtme e Derës me Çelës - Majtas", mk: "Надворешна Рачка на Врата со Клуч - Лево" } },
  { id: "MT-N008", brand: "MAN", price: 22, image: "images/n008.jpg",
    name: { en: "Lower Wheel Cover - Right (TGS)", sq: "Mbulesë e Poshtme e Rrotës - Djathtas (TGS)", mk: "Долен Капак на Тркало - Десно (TGS)" } },
  { id: "MT-N009", brand: "MAN", price: 22, image: "images/n009.jpg",
    name: { en: "Lower Wheel Cover - Left (TGS)", sq: "Mbulesë e Poshtme e Rrotës - Majtas (TGS)", mk: "Долен Капак на Тркало - Лево (TGS)" } },
  { id: "MT-N010", brand: "MAN", price: 132, image: "images/n010.jpg",
    name: { en: "LED Tail Light - Left (Euro 6)", sq: "Llambë e Pasme LED - Majtas (Euro 6)", mk: "LED Задна Светилка - Лево (Euro 6)" } },
  { id: "MT-N011", brand: "MAN", price: 132, image: "images/n011.jpg",
    name: { en: "LED Tail Light - Right (Euro 6)", sq: "Llambë e Pasme LED - Djathtas (Euro 6)", mk: "LED Задна Светилка - Десно (Euro 6)" } },
  { id: "MT-N012", brand: "MAN", price: 19, image: "images/n012.jpg",
    name: { en: "Lower Wheel Cover - Right (TGA Low Cab)", sq: "Mbulesë e Poshtme e Rrotës - Djathtas (TGA Kabinë e Ulët)", mk: "Долен Капак на Тркало - Десно (TGA Низок Кабин)" } },
  { id: "MT-N013", brand: "MAN", price: 32, image: "images/n013.jpg",
    name: { en: "Tail Light with Socket - Right (TGA/TGS/TGX/TGL)", sq: "Llambë e Pasme me Priz - Djathtas", mk: "Задна Светилка со Приклучок - Десно" } },
  { id: "MT-N014", brand: "MAN", price: 10, image: "images/n014.jpg",
    name: { en: "Mudguard Indicator (White)", sq: "Sinjal Treguesi i Blatit (i Bardhë)", mk: "Сигнализатор на Калобран (Бел)" } },
  { id: "MT-N015", brand: "MAN", price: 9.5, image: "images/n015.jpg",
    name: { en: "Mudguard Indicator (Yellow)", sq: "Sinjal Treguesi i Blatit (i Verdhë)", mk: "Сигнализатор на Калобран (Жолт)" } },
  { id: "MT-N016", brand: "MAN", price: 34, image: "images/n016.jpg",
    name: { en: "Battery Cover (TGA Construction / TGS / TGX)", sq: "Kapak i Baterisë (TGA Ndërtimor / TGS / TGX)", mk: "Капак на Батеријата (TGA Градежен / TGS / TGX)" } },
  { id: "MT-N017", brand: "MAN", price: 45, image: "images/n017.jpg",
    name: { en: "Battery Cover (TGA / TGS / TGX)", sq: "Kapak i Baterisë (TGA / TGS / TGX)", mk: "Капак на Батеријата (TGA / TGS / TGX)" } },
  { id: "MT-N018", brand: "MAN", price: 47, image: "images/n018.jpg",
    name: { en: "Lower Step - Right (TGX)", sq: "Shkallë e Poshtme - Djathtas (TGX)", mk: "Долна Скала - Десно (TGX)" } },
  { id: "MT-N019", brand: "MAN", price: 47, image: "images/n019.jpg",
    name: { en: "Lower Step - Left (TGX)", sq: "Shkallë e Poshtme - Majtas (TGX)", mk: "Долна Скала - Лево (TGX)" } },
  { id: "MT-N020", brand: "MAN", price: 221, image: "images/n020.jpg",
    name: { en: "Complete Motorized Mirror - Right (TGX)", sq: "Pasqyrë e Plotë me Motor - Djathtas (TGX)", mk: "Комплетно Огледало со Мотор - Десно (TGX)" } },
  { id: "MT-N021", brand: "MAN", price: 221, image: "images/n021.jpg",
    name: { en: "Complete Motorized Mirror - Left (TGX)", sq: "Pasqyrë e Plotë me Motor - Majtas (TGX)", mk: "Комплетно Огледало со Мотор - Лево (TGX)" } },
  { id: "MT-N022", brand: "MAN", price: 130, image: "images/n022.jpg",
    name: { en: "Lower Bumper - Right (TGX Euro 6)", sq: "Bamper i Poshtëm - Djathtas (TGX Euro 6)", mk: "Долен Браник - Десно (TGX Euro 6)" } },
  { id: "MT-N023", brand: "MAN", price: 130, image: "images/n023.jpg",
    name: { en: "Lower Bumper - Left (TGX Euro 6)", sq: "Bamper i Poshtëm - Majtas (TGX Euro 6)", mk: "Долен Браник - Лево (TGX Euro 6)" } },
  { id: "MT-N024", brand: "MAN", price: 142, image: "images/n024.jpg",
    name: { en: "Upper Bumper with Headlight Washer Hole - Right (TGX Euro 6)", sq: "Bamper i Sipërm me Vrimë për Larje Fenerësh - Djathtas", mk: "Горен Браник со Дупка за Перач на Фарови - Десно" } },
  { id: "MT-N025", brand: "MAN", price: 142, image: "images/n025.jpg",
    name: { en: "Upper Bumper with Headlight Washer Hole - Left (TGX Euro 6)", sq: "Bamper i Sipërm me Vrimë për Larje Fenerësh - Majtas", mk: "Горен Браник со Дупка за Перач на Фарови - Лево" } },

  // ===== SCANIA 4/5/6 SERIES =====
  { id: "MT-S001", brand: "Scania", price: 68, image: "images/s001.jpg",
    name: { en: "Step Housing - Right (5/6 Series)", sq: "Folja e Shkallës - Djathtas (Seria 5/6)", mk: "Куќиште на Скала - Десно (Серија 5/6)" } },
  { id: "MT-S002", brand: "Scania", price: 68, image: "images/s002.jpg",
    name: { en: "Step Housing - Left (5/6 Series)", sq: "Folja e Shkallës - Majtas (Seria 5/6)", mk: "Куќиште на Скала - Лево (Серија 5/6)" } },
  { id: "MT-S003", brand: "Scania", price: 54, image: "images/s003.jpg",
    name: { en: "Front Bumper (4 Series)", sq: "Bamper i Përparmë (Seria 4)", mk: "Преден Браник (Серија 4)" } },
  { id: "MT-S004", brand: "Scania", price: 160, image: "images/s004.jpg",
    name: { en: "Complete Double Mirror - Right (Truck Type)", sq: "Pasqyrë e Plotë Dyfishe - Djathtas (Tip Kamioni)", mk: "Комплетно Двојно Огледало - Десно" } },
  { id: "MT-S005", brand: "Scania", price: 160, image: "images/s005.jpg",
    name: { en: "Complete Double Mirror - Left (Truck Type)", sq: "Pasqyrë e Plotë Dyfishe - Majtas (Tip Kamioni)", mk: "Комплетно Двојно Огледало - Лево" } },
  { id: "MT-S006", brand: "Scania", price: 28, image: "images/s006.jpg",
    name: { en: "Streamline Bumper Corner - Right (2013-2015)", sq: "Cep i Bamperit Streamline - Djathtas (2013-2015)", mk: "Агол на Streamline Браник - Десно (2013-2015)" } },
  { id: "MT-S007", brand: "Scania", price: 28, image: "images/s007.jpg",
    name: { en: "Streamline Bumper Corner - Left (2013-2015)", sq: "Cep i Bamperit Streamline - Majtas (2013-2015)", mk: "Агол на Streamline Браник - Лево (2013-2015)" } },
  { id: "MT-S008", brand: "Scania", price: 34, image: "images/s008.jpg",
    name: { en: "Step Cover - Right (6 Series / Streamline)", sq: "Kapak i Shkallës - Djathtas (Seria 6 / Streamline)", mk: "Капак на Скала - Десно (Серија 6 / Streamline)" } },
  { id: "MT-S009", brand: "Scania", price: 34, image: "images/s009.jpg",
    name: { en: "Step Cover - Left (6 Series / Streamline)", sq: "Kapak i Shkallës - Majtas (Seria 6 / Streamline)", mk: "Капак на Скала - Лево (Серија 6 / Streamline)" } },
  { id: "MT-S010", brand: "Scania", price: 51, image: "images/s010.jpg",
    name: { en: "Cabin Under Front Wheel Rear Fender - Right", sq: "Mbrojtëse e Pasme nën Kabinë - Djathtas", mk: "Заден Калобран под Кабина - Десно" } },
  { id: "MT-S011", brand: "Scania", price: 51, image: "images/s011.jpg",
    name: { en: "Cabin Under Front Wheel Rear Fender - Left", sq: "Mbrojtëse e Pasme nën Kabinë - Majtas", mk: "Заден Калобран под Кабина - Лево" } },
  { id: "MT-S012", brand: "Scania", price: 24, image: "images/s012.jpg",
    name: { en: "Headlight Upper Plastic - Right (5/6 Series R-Cab)", sq: "Plastikë e Sipërme e Fenerit - Djathtas", mk: "Горна Пластика на Фар - Десно" } },
  { id: "MT-S013", brand: "Scania", price: 31, image: "images/s013.jpg",
    name: { en: "Headlight Upper Plastic - Left (5/6 Series R-Cab)", sq: "Plastikë e Sipërme e Fenerit - Majtas", mk: "Горна Пластика на Фар - Лево" } },
  { id: "MT-S014", brand: "Scania", price: 19, image: "images/s014.jpg",
    name: { en: "Exterior Door Handle with Key (4/5/6 Series)", sq: "Dorezë e Jashtme e Derës me Çelës", mk: "Надворешна Рачка на Врата со Клуч" } },
  { id: "MT-S015", brand: "Scania", price: 160, image: "images/s015.jpg",
    name: { en: "Step Housing - Right (Heavy Duty)", sq: "Folja e Shkallës - Djathtas (e Rëndë)", mk: "Куќиште на Скала - Десно (Зајакнато)" } },
  { id: "MT-S016", brand: "Scania", price: 36, image: "images/s016.jpg",
    name: { en: "Wind Deflector Cover - Right (6 Series R-Cab Streamline)", sq: "Kapak i Mbrojtësit të Erës - Djathtas", mk: "Капак на Дефлектор - Десно" } },
  { id: "MT-S017", brand: "Scania", price: 36, image: "images/s017.jpg",
    name: { en: "Wind Deflector Cover - Left (6 Series R-Cab Streamline)", sq: "Kapak i Mbrojtësit të Erës - Majtas", mk: "Капак на Дефлектор - Лево" } },
  { id: "MT-S018", brand: "Scania", price: 147, image: "images/s018.jpg",
    name: { en: "Wind Deflector / Sun Visor - Right (5-6 Series)", sq: "Mbrojtës i Erës / Strehë - Djathtas (Seria 5-6)", mk: "Дефлектор / Сенник - Десно (Серија 5-6)" } },
  { id: "MT-S019", brand: "Scania", price: 147, image: "images/s019.jpg",
    name: { en: "Wind Deflector / Sun Visor - Left (5-6 Series)", sq: "Mbrojtës i Erës / Strehë - Majtas (Seria 5-6)", mk: "Дефлектор / Сенник - Лево (Серија 5-6)" } },
  { id: "MT-S020", brand: "Scania", price: 18, image: "images/s020.jpg",
    name: { en: "Upper Mudguard (Midilli)", sq: "Mbrojtës i Sipërm i Blatit (Midilli)", mk: "Горен Калобран (Midilli)" } },
  { id: "MT-S021", brand: "Scania", price: 30, image: "images/s021.jpg",
    name: { en: "Interior Wind Deflector - Right", sq: "Mbrojtës i Brendshëm i Erës - Djathtas", mk: "Внатрешен Дефлектор - Десно" } },
  { id: "MT-S022", brand: "Scania", price: 30, image: "images/s022.jpg",
    name: { en: "Interior Wind Deflector - Left", sq: "Mbrojtës i Brendshëm i Erës - Majtas", mk: "Внатрешен Дефлектор - Лево" } },
  { id: "MT-S023", brand: "Scania", price: 160, image: "images/s023.jpg",
    name: { en: "Step Housing - Left (Heavy Duty)", sq: "Folja e Shkallës - Majtas (e Rëndë)", mk: "Куќиште на Скала - Лево (Зајакнато)" } },
  { id: "MT-S024", brand: "Scania", price: 18, image: "images/s024.jpg",
    name: { en: "Upper Mudguard (4/5/6 Series)", sq: "Mbrojtës i Sipërm i Blatit (Seria 4/5/6)", mk: "Горен Калобран (Серија 4/5/6)" } },

  // ===== VOLVO FH / FM =====
  { id: "MT-V001", brand: "Volvo", price: 13, image: "images/v001.jpg",
    name: { en: "Front Wheel Arch Inner Fender - Right", sq: "Mbrojtëse e Brendshme e Rrotës - Djathtas", mk: "Внатрешен Калобран на Преден Тркало - Десно" } },
  { id: "MT-V002", brand: "Volvo", price: 13, image: "images/v002.jpg",
    name: { en: "Front Wheel Arch Inner Fender - Left", sq: "Mbrojtëse e Brendshme e Rrotës - Majtas", mk: "Внатрешен Калобран на Преден Тркало - Лево" } },
  { id: "MT-V003", brand: "Volvo", price: 190, image: "images/v003.jpg",
    name: { en: "Complete Side Mirror - Right (FH4)", sq: "Pasqyrë Anësore e Plotë - Djathtas (FH4)", mk: "Комплетно Странично Огледало - Десно (FH4)" } },
  { id: "MT-V004", brand: "Volvo", price: 190, image: "images/v004.jpg",
    name: { en: "Complete Side Mirror - Left (FH4)", sq: "Pasqyrë Anësore e Plotë - Majtas (FH4)", mk: "Комплетно Странично Огледало - Лево (FH4)" } },
  { id: "MT-V005", brand: "Volvo", price: 124, image: "images/v005.jpg",
    name: { en: "Battery Cover (FH4)", sq: "Kapak i Baterisë (FH4)", mk: "Капак на Батеријата (FH4)" } },
  { id: "MT-V006", brand: "Volvo", price: 52, image: "images/v006.jpg",
    name: { en: "Headlight Frame - Right (FH version 4)", sq: "Korniza e Fenerit - Djathtas (FH versioni 4)", mk: "Рамка на Фар - Десно (FH верзија 4)" } },
  { id: "MT-V007", brand: "Volvo", price: 52, image: "images/v007.jpg",
    name: { en: "Headlight Frame - Left (FH version 4)", sq: "Korniza e Fenerit - Majtas (FH versioni 4)", mk: "Рамка на Фар - Лево (FH верзија 4)" } },
  { id: "MT-V008", brand: "Volvo", price: 3, image: "images/v008.jpg",
    name: { en: "Fender Rubber Strip (FH version 3-4)", sq: "Shirit Gome i Mbrojtësit (FH versioni 3-4)", mk: "Гумена Лента за Калобран (FH верзија 3-4)" } },
  { id: "MT-V009", brand: "Volvo", price: 16, image: "images/v009.jpg",
    name: { en: "Upper Fender / Top Wing (FH/FM version 3/4)", sq: "Mbrojtës i Sipërm i Blatit (FH/FM v3/4)", mk: "Горен Калобран (FH/FM в3/4)" } },
  { id: "MT-V010", brand: "Volvo", price: 32, image: "images/v010.jpg",
    name: { en: "Center Front Bumper (FH/FM, alt version)", sq: "Bamper i Përparmë Qendror (FH/FM, version alternativ)", mk: "Централен Преден Браник (FH/FM, алтернативна верзија)" } },
  { id: "MT-V011", brand: "Volvo", price: 26, image: "images/v011.jpg",
    name: { en: "Front Bumper Corner - Right (FH version 4)", sq: "Cep i Bamperit të Përparmë - Djathtas (FH v4)", mk: "Агол на Преден Браник - Десно (FH в4)" } },
  { id: "MT-V012", brand: "Volvo", price: 13, image: "images/v012.jpg",
    name: { en: "Front Bumper Corner - Left (FH version 4)", sq: "Cep i Bamperit të Përparmë - Majtas (FH v4)", mk: "Агол на Преден Браник - Лево (FH в4)" } },
  { id: "MT-V013", brand: "Volvo", price: 125, image: "images/v013.jpg",
    name: { en: "Front Wheel Outer Fender - Right (FH version 4/5)", sq: "Mbrojtës i Jashtëm i Rrotës - Djathtas (FH v4/5)", mk: "Надворешен Калобран на Преден Тркало - Десно (FH в4/5)" } },
  { id: "MT-V014", brand: "Volvo", price: 125, image: "images/v014.jpg",
    name: { en: "Front Wheel Outer Fender - Left (FH version 4/5)", sq: "Mbrojtës i Jashtëm i Rrotës - Majtas (FH v4/5)", mk: "Надворешен Калобран на Преден Тркало - Лево (FH в4/5)" } },
  { id: "MT-V015", brand: "Volvo", price: 27, image: "images/v015.jpg",
    name: { en: "Lower Step / Footboard - Left (FH version 4-5)", sq: "Shkallë e Poshtme - Majtas (FH v4-5)", mk: "Долна Скала - Лево (FH в4-5)" } },
  { id: "MT-V016", brand: "Volvo", price: 28, image: "images/v016.jpg",
    name: { en: "Mirror Back Cover - Right (FH4)", sq: "Kapak i Pasmë i Pasqyrës - Djathtas (FH4)", mk: "Заден Капак на Огледало - Десно (FH4)" } },
  { id: "MT-V017", brand: "Volvo", price: 28, image: "images/v017.jpg",
    name: { en: "Mirror Back Cover - Left (FH4)", sq: "Kapak i Pasmë i Pasqyrës - Majtas (FH4)", mk: "Заден Капак на Огледало - Лево (FH4)" } },
  { id: "MT-V018", brand: "Volvo", price: 134, image: "images/v018.jpg",
    name: { en: "Tail Light - Right (FH4)", sq: "Llambë e Pasme - Djathtas (FH4)", mk: "Задна Светилка - Десно (FH4)" } },
  { id: "MT-V019", brand: "Volvo", price: 134, image: "images/v019.jpg",
    name: { en: "Tail Light - Left (FH4)", sq: "Llambë e Pasme - Majtas (FH4)", mk: "Задна Светилка - Лево (FH4)" } },
  { id: "MT-V020", brand: "Volvo", price: 38, image: "images/v020.jpg",
    name: { en: "Center Front Bumper (FH/FM version 4/5)", sq: "Bamper i Përparmë Qendror (FH/FM v4/5)", mk: "Централен Преден Браник (FH/FM в4/5)" } },
  { id: "MT-V022", brand: "Volvo", price: 32.5, image: "images/v022.jpg",
    name: { en: "Lower Step / Footboard - Right (FH version 4-5)", sq: "Shkallë e Poshtme - Djathtas (FH v4-5)", mk: "Долна Скала - Десно (FH в4-5)" } },
];
