const PRODUCTS = [
  // Mercedes
  { id: "MT-001", name: { sq: "Panel i Derës së Përparme - Majtas", mk: "Предна Врата Панел - Лево", en: "Front Door Panel - Left" }, brand: "Mercedes", price: 59, image: "images/p001.jpg" },
  { id: "MT-002", name: { sq: "Panel i Derës së Përparme - Djathtas", mk: "Предна Врата Панел - Десно", en: "Front Door Panel - Right" }, brand: "Mercedes", price: 59, image: "images/p002.jpg" },
  { id: "MT-003", name: { sq: "Mbrojtëse e Pasme - Majtas", mk: "Задна Калобран - Лево", en: "Rear Mudguard - Left" }, brand: "Mercedes", price: 45, image: "images/p003.jpg" },
  { id: "MT-004", name: { sq: "Mbrojtëse e Pasme - Djathtas", mk: "Задна Калобран - Десно", en: "Rear Mudguard - Right" }, brand: "Mercedes", price: 45, image: "images/p004.jpg" },
  { id: "MT-005", name: { sq: "Llambë e Pasme - Majtas", mk: "Задна Светилка - Лево", en: "Tail Light - Left" }, brand: "Mercedes", price: 79, image: "images/p005.jpg" },
  { id: "MT-006", name: { sq: "Llambë e Pasme - Djathtas", mk: "Задна Светилка - Десно", en: "Tail Light - Right" }, brand: "Mercedes", price: 79, image: "images/p006.jpg" },
  { id: "MT-007", name: { sq: "Dorezë e Jashtme e Derës", mk: "Надворешна Рачка на Вратата", en: "Exterior Door Handle" }, brand: "Mercedes", price: 38, image: "images/p007.jpg" },
  { id: "MT-008", name: { sq: "Paneli i Strehës", mk: "Панел на Стреа", en: "Sun Visor Panel" }, brand: "Mercedes", price: 95, image: "images/p008.jpg" },
  { id: "MT-009", name: { sq: "Mbrojtës i Pragut", mk: "Заштита на Прагот", en: "Step Guard" }, brand: "Mercedes", price: 32, image: "images/p009.jpg" },
  { id: "MT-010", name: { sq: "Kapak i Rezervuarit", mk: "Капак на Резервоарот", en: "Fuel Tank Cover" }, brand: "Mercedes", price: 28, image: "images/p010.jpg" },
  { id: "MT-011", name: { sq: "Panel Anësor i Kabinës", mk: "Страничен Панел на Кабина", en: "Cabin Side Panel" }, brand: "Mercedes", price: 89, image: "images/p011.jpg" },
  { id: "MT-012", name: { sq: "Mbrojtëse e Blatit - Përpara", mk: "Преден Калобран", en: "Front Mudguard" }, brand: "Mercedes", price: 42, image: "images/p012.jpg" },

  // MAN
  { id: "MT-013", name: { sq: "Grilë e Përparme", mk: "Предна Решетка", en: "Front Grille" }, brand: "MAN", price: 110, image: "images/p013.jpg" },
  { id: "MT-014", name: { sq: "Bamper i Përparmë - Majtas", mk: "Преден Браник - Лево", en: "Front Bumper - Left" }, brand: "MAN", price: 85, image: "images/p014.jpg" },
  { id: "MT-015", name: { sq: "Bamper i Përparmë - Djathtas", mk: "Преден Браник - Десно", en: "Front Bumper - Right" }, brand: "MAN", price: 85, image: "images/p015.jpg" },
  { id: "MT-016", name: { sq: "Llambë e Përparme", mk: "Предна Светилка", en: "Front Light Assembly" }, brand: "MAN", price: 129, image: "images/p016.jpg" },
  { id: "MT-017", name: { sq: "Paneli i Derës - Majtas", mk: "Панел на Врата - Лево", en: "Door Panel - Left" }, brand: "MAN", price: 67, image: "images/p017.jpg" },
  { id: "MT-018", name: { sq: "Paneli i Derës - Djathtas", mk: "Панел на Врата - Десно", en: "Door Panel - Right" }, brand: "MAN", price: 67, image: "images/p018.jpg" },
  { id: "MT-019", name: { sq: "Dorezë e Jashtme", mk: "Надворешна Рачка", en: "Exterior Handle" }, brand: "MAN", price: 35, image: "images/p019.jpg" },
  { id: "MT-020", name: { sq: "Mbrojtës i Blatit - Pasme", mk: "Заден Калобран", en: "Rear Mudguard" }, brand: "MAN", price: 49, image: "images/p020.jpg" },
  { id: "MT-021", name: { sq: "Panel i Strehës Anësore", mk: "Страничен Сенник Панел", en: "Side Visor Panel" }, brand: "MAN", price: 72, image: "images/p021.jpg" },
  { id: "MT-022", name: { sq: "Kapak i Motorit", mk: "Капак на Моторот", en: "Engine Hood Cover" }, brand: "MAN", price: 145, image: "images/p022.jpg" },
  { id: "MT-023", name: { sq: "Shkallë Hyrëse", mk: "Влезна Скала", en: "Entry Step" }, brand: "MAN", price: 55, image: "images/p023.jpg" },
  { id: "MT-024", name: { sq: "Mbrojtëse e Pragut", mk: "Заштита на Прагот", en: "Sill Protector" }, brand: "MAN", price: 30, image: "images/p024.jpg" },

  // Volvo
  { id: "MT-025", name: { sq: "Bamper i Përparmë - Qendror", mk: "Преден Браник - Центар", en: "Front Bumper - Center" }, brand: "Volvo", price: 99, image: "images/p025.jpg" },
  { id: "MT-026", name: { sq: "Bamper i Përparmë - Majtas", mk: "Преден Браник - Лево", en: "Front Bumper - Left" }, brand: "Volvo", price: 79, image: "images/p026.jpg" },
  { id: "MT-027", name: { sq: "Bamper i Përparmë - Djathtas", mk: "Преден Браник - Десно", en: "Front Bumper - Right" }, brand: "Volvo", price: 79, image: "images/p027.jpg" },
  { id: "MT-028", name: { sq: "Grilë e Qendrës", mk: "Централна Решетка", en: "Center Grille" }, brand: "Volvo", price: 92, image: "images/p028.jpg" },
  { id: "MT-029", name: { sq: "Llambë e Pasme - Majtas", mk: "Задна Светилка - Лево", en: "Tail Light - Left" }, brand: "Volvo", price: 88, image: "images/p029.jpg" },
  { id: "MT-030", name: { sq: "Llambë e Pasme - Djathtas", mk: "Задна Светилка - Десно", en: "Tail Light - Right" }, brand: "Volvo", price: 88, image: "images/p030.jpg" },
  { id: "MT-031", name: { sq: "Paneli i Fenderit", mk: "Панел на Бранник", en: "Fender Panel" }, brand: "Volvo", price: 62, image: "images/p031.jpg" },
  { id: "MT-032", name: { sq: "Dorezë e Derës", mk: "Рачка на Врата", en: "Door Handle" }, brand: "Volvo", price: 41, image: "images/p032.jpg" },
  { id: "MT-033", name: { sq: "Mbrojtëse Anësore", mk: "Страничен Штитник", en: "Side Protector" }, brand: "Volvo", price: 55, image: "images/p033.jpg" },
  { id: "MT-034", name: { sq: "Shkallë Hyrëse - Majtas", mk: "Влезна Скала - Лево", en: "Entry Step - Left" }, brand: "Volvo", price: 48, image: "images/p034.jpg" },
  { id: "MT-035", name: { sq: "Shkallë Hyrëse - Djathtas", mk: "Влезна Скала - Десно", en: "Entry Step - Right" }, brand: "Volvo", price: 48, image: "images/p035.jpg" },
  { id: "MT-036", name: { sq: "Kapak i Rezervuarit", mk: "Капак на Резервоарот", en: "Tank Cap Cover" }, brand: "Volvo", price: 25, image: "images/p036.jpg" },

  // Scania
  { id: "MT-037", name: { sq: "Bamper i Përparmë", mk: "Преден Браник", en: "Front Bumper" }, brand: "Scania", price: 120, image: "images/p037.jpg" },
  { id: "MT-038", name: { sq: "Shtojcë Bamperit - Majtas", mk: "Додаток за Браник - Лево", en: "Bumper Extension - Left" }, brand: "Scania", price: 65, image: "images/p038.jpg" },
  { id: "MT-039", name: { sq: "Shtojcë Bamperit - Djathtas", mk: "Додаток за Браник - Десно", en: "Bumper Extension - Right" }, brand: "Scania", price: 65, image: "images/p039.jpg" },
  { id: "MT-040", name: { sq: "Mbrojtëse e Blatit - Majtas", mk: "Калобран - Лево", en: "Mudguard - Left" }, brand: "Scania", price: 39, image: "images/p040.jpg" },
  { id: "MT-041", name: { sq: "Mbrojtëse e Blatit - Djathtas", mk: "Калобран - Десно", en: "Mudguard - Right" }, brand: "Scania", price: 39, image: "images/p041.jpg" },
  { id: "MT-042", name: { sq: "Paneli i Derës", mk: "Панел на Врата", en: "Door Panel" }, brand: "Scania", price: 75, image: "images/p042.jpg" },
  { id: "MT-043", name: { sq: "Dorezë e Derës", mk: "Рачка на Врата", en: "Door Handle" }, brand: "Scania", price: 38, image: "images/p043.jpg" },
  { id: "MT-044", name: { sq: "Llambë e Pasme", mk: "Задна Светилка", en: "Rear Light" }, brand: "Scania", price: 95, image: "images/p044.jpg" },
  { id: "MT-045", name: { sq: "Panel Anësor i Poshtëm", mk: "Долен Страничен Панел", en: "Lower Side Panel" }, brand: "Scania", price: 58, image: "images/p045.jpg" },
  { id: "MT-046", name: { sq: "Mbrojtës Balte - Pasme", mk: "Заден Калобран", en: "Rear Mud Flap Bracket" }, brand: "Scania", price: 29, image: "images/p046.jpg" },

  // DAF
  { id: "MT-047", name: { sq: "Bamper i Përparmë - Majtas", mk: "Преден Браник - Лево", en: "Front Bumper - Left" }, brand: "DAF", price: 78, image: "images/p047.jpg" },
  { id: "MT-048", name: { sq: "Bamper i Përparmë - Djathtas", mk: "Преден Браник - Десно", en: "Front Bumper - Right" }, brand: "DAF", price: 78, image: "images/p048.jpg" },
  { id: "MT-049", name: { sq: "Kapak i Kabinës", mk: "Капак на Кабина", en: "Cabin Hood" }, brand: "DAF", price: 135, image: "images/p049.jpg" },
  { id: "MT-050", name: { sq: "Paneli i Derës - Majtas", mk: "Панел на Врата - Лево", en: "Door Panel - Left" }, brand: "DAF", price: 69, image: "images/p050.jpg" },
  { id: "MT-051", name: { sq: "Paneli i Derës - Djathtas", mk: "Панел на Врата - Десно", en: "Door Panel - Right" }, brand: "DAF", price: 69, image: "images/p051.jpg" },
  { id: "MT-052", name: { sq: "Grilë e Sipërme", mk: "Горна Решетка", en: "Upper Grille" }, brand: "DAF", price: 85, image: "images/p052.jpg" },
  { id: "MT-053", name: { sq: "Llambë Ndriçuese Anësore", mk: "Странична Светилка", en: "Side Marker Light" }, brand: "DAF", price: 22, image: "images/p053.jpg" },
  { id: "MT-054", name: { sq: "Dorezë e Derës - Majtas", mk: "Рачка на Врата - Лево", en: "Door Handle - Left" }, brand: "DAF", price: 36, image: "images/p054.jpg" },
  { id: "MT-055", name: { sq: "Mbrojtëse e Blatit", mk: "Калобран", en: "Mudguard" }, brand: "DAF", price: 44, image: "images/p055.jpg" },

  // Iveco
  { id: "MT-056", name: { sq: "Bamper i Përparmë", mk: "Преден Браник", en: "Front Bumper" }, brand: "Iveco", price: 88, image: "images/p056.jpg" },
  { id: "MT-057", name: { sq: "Paneli Anësor - Majtas", mk: "Страничен Панел - Лево", en: "Side Panel - Left" }, brand: "Iveco", price: 72, image: "images/p057.jpg" },
  { id: "MT-058", name: { sq: "Paneli Anësor - Djathtas", mk: "Страничен Панел - Десно", en: "Side Panel - Right" }, brand: "Iveco", price: 72, image: "images/p058.jpg" },
  { id: "MT-059", name: { sq: "Dorezë e Derës", mk: "Рачка на Врата", en: "Door Handle" }, brand: "Iveco", price: 33, image: "images/p059.jpg" },
  { id: "MT-060", name: { sq: "Mbrojtëse e Blatit - Majtas", mk: "Калобран - Лево", en: "Mudguard - Left" }, brand: "Iveco", price: 41, image: "images/p060.jpg" },
  { id: "MT-061", name: { sq: "Mbrojtëse e Blatit - Djathtas", mk: "Калобран - Десно", en: "Mudguard - Right" }, brand: "Iveco", price: 41, image: "images/p061.jpg" },
  { id: "MT-062", name: { sq: "Llambë e Pasme - Majtas", mk: "Задна Светилка - Лево", en: "Rear Tail Light - Left" }, brand: "Iveco", price: 75, image: "images/p062.jpg" },
  { id: "MT-063", name: { sq: "Llambë e Pasme - Djathtas", mk: "Задна Светилка - Десно", en: "Rear Tail Light - Right" }, brand: "Iveco", price: 75, image: "images/p063.jpg" },
  { id: "MT-064", name: { sq: "Shkallë Hyrëse", mk: "Влезна Скала", en: "Entry Step" }, brand: "Iveco", price: 52, image: "images/p064.jpg" },

  // Renault
  { id: "MT-065", name: { sq: "Bamper i Përparmë - Majtas", mk: "Преден Браник - Лево", en: "Front Bumper - Left" }, brand: "Renault", price: 82, image: "images/p065.jpg" },
  { id: "MT-066", name: { sq: "Bamper i Përparmë - Djathtas", mk: "Преден Браник - Десно", en: "Front Bumper - Right" }, brand: "Renault", price: 82, image: "images/p066.jpg" },
  { id: "MT-067", name: { sq: "Panel i Kabinës - Majtas", mk: "Панел на Кабина - Лево", en: "Cabin Panel - Left" }, brand: "Renault", price: 91, image: "images/p067.jpg" },
  { id: "MT-068", name: { sq: "Panel i Kabinës - Djathtas", mk: "Панел на Кабина - Десно", en: "Cabin Panel - Right" }, brand: "Renault", price: 91, image: "images/p068.jpg" },
  { id: "MT-069", name: { sq: "Mbrojtëse e Blatit", mk: "Калобран", en: "Mudguard" }, brand: "Renault", price: 38, image: "images/p069.jpg" },
  { id: "MT-070", name: { sq: "Dorezë e Derës", mk: "Рачка на Врата", en: "Door Handle" }, brand: "Renault", price: 34, image: "images/p070.jpg" },
  { id: "MT-071", name: { sq: "Llambë e Pasme", mk: "Задна Светилка", en: "Rear Light" }, brand: "Renault", price: 82, image: "images/p071.jpg" },
  { id: "MT-072", name: { sq: "Grilë e Përparme", mk: "Предна Решетка", en: "Front Grille" }, brand: "Renault", price: 98, image: "images/p072.jpg" },
  { id: "MT-073", name: { sq: "Kapak i Rezervuarit", mk: "Капак на Резервоар", en: "Fuel Tank Cover" }, brand: "Renault", price: 27, image: "images/p073.jpg" },
  { id: "MT-074", name: { sq: "Shkallë Hyrëse - Majtas", mk: "Влезна Скала - Лево", en: "Entry Step - Left" }, brand: "Renault", price: 46, image: "images/p074.jpg" },
  { id: "MT-075", name: { sq: "Shkallë Hyrëse - Djathtas", mk: "Влезна Скала - Десно", en: "Entry Step - Right" }, brand: "Renault", price: 46, image: "images/p075.jpg" },
  { id: "MT-076", name: { sq: "Paneli i Derës - Majtas", mk: "Панел на Врата - Лево", en: "Door Panel - Left" }, brand: "Renault", price: 66, image: "images/p076.jpg" },
];
